/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.model.vo.Equipamento;
import br.com.jsampaio.sigem.model.vo.Equipamentos;
import br.com.jsampaio.sigem.util.Configs;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaCadastrarEquipamento extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastrarEquipamento
     */
    public TelaCadastrarEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnCadastrarEquip = new javax.swing.JButton();
        jcbSituacao = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtTipoEquip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumTombamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbDataAcesso = new javax.swing.JLabel();

        setBackground(GraphicsConstants.COR_FUNDO);

        jPanel1.setBackground(GraphicsConstants.COR_FUNDO);

        btnLimpar.setFont(GraphicsConstants.FONT_BOTAO);
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/master-clean2.png"))); // NOI18N
        btnLimpar.setText(Configs.ConfigTela.getConfig("btnLimparEquipamento"));
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCadastrarEquip.setFont(GraphicsConstants.FONT_BOTAO);
        btnCadastrarEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/save-icon-52.png"))); // NOI18N
        btnCadastrarEquip.setText(Configs.ConfigTela.getConfig("btnSalvarEquipamento"));
        btnCadastrarEquip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbSituacao.setFont(GraphicsConstants.FONT_INPUT);
        jcbSituacao.setModel(new DefaultComboBoxModel<String>(Equipamentos.STATUS));
        jcbSituacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(GraphicsConstants.FONT_LABEL);
        jLabel10.setText(Configs.ConfigTela.getConfig("lbStatusEquipamento"));

        jLabel19.setFont(GraphicsConstants.FONT_LABEL);
        jLabel19.setText(Configs.ConfigTela.getConfig("lbDescricaoEquipamento"));

        txtDescricao.setFont(GraphicsConstants.FONT_INPUT);
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        txtTipoEquip.setFont(GraphicsConstants.FONT_INPUT);
        txtTipoEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoEquipActionPerformed(evt);
            }
        });

        jLabel8.setFont(GraphicsConstants.FONT_LABEL);
        jLabel8.setText(Configs.ConfigTela.getConfig("lbTipoEquipamento"));

        jLabel9.setFont(GraphicsConstants.FONT_LABEL);
        jLabel9.setText(Configs.ConfigTela.getConfig("lbNumTomb"));

        txtNumTombamento.setFont(GraphicsConstants.FONT_INPUT);
        txtNumTombamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTombamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoEquip)
                    .addComponent(txtDescricao)
                    .addComponent(jcbSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNumTombamento))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(GraphicsConstants.FONT_TITULO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(Configs.ConfigTela.getConfig("lbTituloEquipamento"));

        lbDataAcesso.setForeground(new java.awt.Color(153, 153, 153));
        lbDataAcesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDataAcesso.setText("Acesso em");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addComponent(lbDataAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDataAcesso)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void preencherCamposAtualizacao(Equipamento equipamento) {
        this.txtNumTombamento.setText(String.valueOf(equipamento.getNumeroTombamento()));
        this.txtDescricao.setText(equipamento.getDescricao());
        this.txtTipoEquip.setText(equipamento.getTipo());
        this.jcbSituacao.setSelectedItem(equipamento.getStatus());
    }
    
    public JButton getBtnCadastrarEquip() {
        return btnCadastrarEquip;
    }

    public JButton getBtnLimpar() {
        return btnLimpar;
    }

    public JComboBox getJcbSituacao() {
        return jcbSituacao;
    }

    public JTextField getTxtDescricao() {
        return txtDescricao;
    }

    public JTextField getTxtNumTombamento() {
        return txtNumTombamento;
    }

    public JTextField getTxtTipoEquip() {
        return txtTipoEquip;
    }

    public JLabel getLbDataAcesso() {
        return lbDataAcesso;
    }
    
    private void txtNumTombamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTombamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTombamentoActionPerformed

    private void txtTipoEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoEquipActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEquip;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbSituacao;
    private javax.swing.JLabel lbDataAcesso;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNumTombamento;
    private javax.swing.JTextField txtTipoEquip;
    // End of variables declaration//GEN-END:variables
}
