/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.model.vo.Equipamentos;
import br.com.jsampaio.sigem.util.Configs;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaRelatorioEquipamento extends javax.swing.JPanel {

    /**
     * Creates new form TelaRelatorioEquipamento
     */
    public TelaRelatorioEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jcbFiltro = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipamento = new javax.swing.JTable();
        jpPaginacao = new JPanel();
        btnGerarRelatorio = new javax.swing.JButton();
        btnGerarGrafico = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLimparCampos = new javax.swing.JButton();
        lbDataAcesso = new javax.swing.JLabel();

        setBackground(GraphicsConstants.COR_FUNDO);

        jLabel2.setFont(GraphicsConstants.FONT_TITULO);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(Configs.ConfigTela.getConfig("lbTituloTelatorioEquipamento"));

        txtPesquisa.setFont(GraphicsConstants.FONT_INPUT);

        jcbFiltro.setFont(GraphicsConstants.FONT_INPUT);
        jcbFiltro.setModel(new DefaultComboBoxModel<String>(Equipamentos.STATUS_1));
        jcbFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbFiltro.setFocusable(false);

        jPanel2.setBackground(GraphicsConstants.COR_FUNDO);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(GraphicsConstants.COR_FUNDO, 1, true));

        tblEquipamento.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Tombamento", "Tipo", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEquipamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblEquipamento.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblEquipamento.setRowHeight(30);
        tblEquipamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEquipamento.setShowHorizontalLines(false);
        tblEquipamento.setShowVerticalLines(false);
        tblEquipamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblEquipamento);

        jpPaginacao.setBackground(GraphicsConstants.COR_FUNDO);
        jpPaginacao.setPreferredSize(new java.awt.Dimension(529, 42));

        javax.swing.GroupLayout jpPaginacaoLayout = new javax.swing.GroupLayout(jpPaginacao);
        jpPaginacao.setLayout(jpPaginacaoLayout);
        jpPaginacaoLayout.setHorizontalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        jpPaginacaoLayout.setVerticalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        btnGerarRelatorio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/ios7-printer.png"))); // NOI18N
        btnGerarRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerarRelatorio.setFocusable(false);

        btnGerarGrafico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGerarGrafico.setText("Gerar Gráfico");
        btnGerarGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerarGrafico.setFocusable(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLimparCampos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/master-clean2.png"))); // NOI18N
        btnLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparCampos.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGerarRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGerarGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );

        lbDataAcesso.setForeground(new java.awt.Color(153, 153, 153));
        lbDataAcesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDataAcesso.setText("Acesso em");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDataAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbDataAcesso)
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public JComboBox getJcbFiltro() {
        return jcbFiltro;
    }

    public JPanel getJpPaginacao() {
        return jpPaginacao;
    }

    public JTable getTblEquipamento() {
        return tblEquipamento;
    }

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    public JLabel getLbDataAcesso() {
        return lbDataAcesso;
    }

    public JButton getBtnGerarGrafico() {
        return btnGerarGrafico;
    }

    public JButton getBtnGerarRelatorio() {
        return btnGerarRelatorio;
    }

    public JButton getBtnLimparCampos() {
        return btnLimparCampos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarGrafico;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox jcbFiltro;
    private javax.swing.JPanel jpPaginacao;
    private javax.swing.JLabel lbDataAcesso;
    private javax.swing.JTable tblEquipamento;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
