/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.model.vo.RequisicaoMateriais;
import br.com.jsampaio.sigem.util.Configs;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaLiberarMaterial extends javax.swing.JPanel {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaLiberarMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRequisitante = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();
        btnSelecionarMaterial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlMateriais = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        btnRemoverMaterial = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnLiberarMaterial = new javax.swing.JButton();
        lbAcesso = new javax.swing.JLabel();
        btnPesquisarRequisitante = new javax.swing.JButton();
        txtRecebedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSelecionarRecebedor = new javax.swing.JButton();

        setBackground(GraphicsConstants.COR_FUNDO);
        setPreferredSize(new java.awt.Dimension(893, 460));

        jLabel1.setFont(GraphicsConstants.FONT_TITULO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(Configs.ConfigTela.getConfig("lbTituloRequisicaoMaterial"));

        jLabel7.setFont(GraphicsConstants.FONT_LABEL);
        jLabel7.setText(Configs.ConfigTela.getConfig("lbRequisitanteMaterial"));

        txtRequisitante.setEditable(false);
        txtRequisitante.setFont(GraphicsConstants.FONT_INPUT);
        txtRequisitante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(GraphicsConstants.FONT_LABEL);
        jLabel9.setText(Configs.ConfigTela.getConfig("lbUnidadeRequisitanteMaterial"));

        txtUnidade.setEditable(false);
        txtUnidade.setFont(GraphicsConstants.FONT_INPUT);

        btnSelecionarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/lupa2.png"))); // NOI18N
        btnSelecionarMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlMateriais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlMateriais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlMateriais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jlMateriais);

        jLabel8.setFont(GraphicsConstants.FONT_LABEL);
        jLabel8.setText(Configs.ConfigTela.getConfig("lbMateriaisRequisitados"));

        btnRemoverMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/ios7-trash-mini.png"))); // NOI18N
        btnRemoverMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLimpar.setFont(GraphicsConstants.FONT_BOTAO);
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/master-clean.png"))); // NOI18N
        btnLimpar.setText(Configs.ConfigTela.getConfig("btnLimparRequisicao"));
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLiberarMaterial.setFont(GraphicsConstants.FONT_BOTAO);
        btnLiberarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/liberar.png"))); // NOI18N
        btnLiberarMaterial.setText(Configs.ConfigTela.getConfig("btnLiberarMaterial"));
        btnLiberarMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLiberarMaterial.setMargin(new java.awt.Insets(2, 2, 2, 2));

        lbAcesso.setForeground(new java.awt.Color(153, 153, 153));
        lbAcesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAcesso.setText("Acesso em");

        btnPesquisarRequisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/lupa2.png"))); // NOI18N
        btnPesquisarRequisitante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtRecebedor.setEditable(false);
        txtRecebedor.setFont(GraphicsConstants.FONT_INPUT);
        txtRecebedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(GraphicsConstants.FONT_LABEL);
        jLabel2.setText(Configs.ConfigTela.getConfig("lbRecebedorMaterial"));

        btnSelecionarRecebedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/lupa2.png"))); // NOI18N
        btnSelecionarRecebedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(163, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLiberarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSelecionarMaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoverMaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRecebedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                                    .addComponent(txtRequisitante, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPesquisarRequisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSelecionarRecebedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRequisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(btnPesquisarRequisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecebedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarRecebedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelecionarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnRemoverMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLiberarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lbAcesso)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnPesquisarRequisitante() {
        return btnPesquisarRequisitante;
    }

    public JTextField getTxtUnidade() {
        return txtUnidade;
    }

    public JTextField getTxtRequisitante() {
        return txtRequisitante;
    }

    public JButton getBtnSelecionarMaterial() {
        return btnSelecionarMaterial;
    }
    
    public JList<RequisicaoMateriais> getJlMateriais() {
        return jlMateriais;
    }

    public JButton getBtnRemoverMaterial() {
        return btnRemoverMaterial;
    }

    public JButton getBtnLiberarMaterial() {
        return btnLiberarMaterial;
    }

    public JButton getBtnLimpar() {
        return btnLimpar;
    }

    public JLabel getLbAcesso() {
        return lbAcesso;
    }

    public JTextField getTxtRecebedor() {
        return txtRecebedor;
    }

    public JButton getBtnSelecionarRecebedor() {
        return btnSelecionarRecebedor;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiberarMaterial;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarRequisitante;
    private javax.swing.JButton btnRemoverMaterial;
    private javax.swing.JButton btnSelecionarMaterial;
    private javax.swing.JButton btnSelecionarRecebedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<RequisicaoMateriais> jlMateriais;
    private javax.swing.JLabel lbAcesso;
    private javax.swing.JTextField txtRecebedor;
    private javax.swing.JTextField txtRequisitante;
    private javax.swing.JTextField txtUnidade;
    // End of variables declaration//GEN-END:variables
}
