/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.model.vo.Equipamentos;
import br.com.jsampaio.sigem.model.vo.Pessoa;
import br.com.jsampaio.sigem.model.vo.Pessoa.Tipo;
import br.com.jsampaio.sigem.util.Configs;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
        this.jcbTipo.removeItem(Tipo.Administrador);
        this.jcbTipo.removeItem(Tipo.Usuario);
     
        this.jcbSituacao.setVisible(false);
        this.jcbTipo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbDataAcesso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdministrador = new javax.swing.JTable();
        jpPaginacao = new JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnPessoas = new javax.swing.JButton();
        btnEquipamentos = new javax.swing.JButton();
        btnMateriais = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        jcbSituacao = new javax.swing.JComboBox();
        jcbTipo = new javax.swing.JComboBox<>();
        jcbAtivo = new javax.swing.JComboBox<>();
        txtPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLimparFiltros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnImprimir = new javax.swing.JButton();

        setBackground(GraphicsConstants.COR_FUNDO);

        jLabel1.setFont(GraphicsConstants.FONT_TITULO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(Configs.ConfigTela.getConfig("lbTituloPainel"));

        lbDataAcesso.setForeground(new java.awt.Color(153, 153, 153));
        lbDataAcesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDataAcesso.setText("Acesso em");

        jPanel1.setBackground(GraphicsConstants.COR_FUNDO);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(GraphicsConstants.COR_FUNDO, 1, true));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblAdministrador.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Painel de Controle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblAdministrador.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblAdministrador.setRowHeight(30);
        tblAdministrador.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAdministrador.setShowHorizontalLines(false);
        tblAdministrador.setShowVerticalLines(false);
        tblAdministrador.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAdministrador);
        if (tblAdministrador.getColumnModel().getColumnCount() > 0) {
            tblAdministrador.getColumnModel().getColumn(0).setResizable(false);
        }

        jpPaginacao.setBackground(GraphicsConstants.COR_FUNDO);
        jpPaginacao.setPreferredSize(new java.awt.Dimension(529, 42));

        javax.swing.GroupLayout jpPaginacaoLayout = new javax.swing.GroupLayout(jpPaginacao);
        jpPaginacao.setLayout(jpPaginacaoLayout);
        jpPaginacaoLayout.setHorizontalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        jpPaginacaoLayout.setVerticalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnUsuarios.setMnemonic('U');
        btnUsuarios.setText(Configs.ConfigTela.getConfig("btnPainelUsuario"));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setFocusable(false);
        btnUsuarios.setName("Usuários"); // NOI18N

        btnPessoas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPessoas.setMnemonic('P');
        btnPessoas.setText(Configs.ConfigTela.getConfig("btnPainelPessoa"));
        btnPessoas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPessoas.setFocusable(false);
        btnPessoas.setName("Pessoas"); // NOI18N

        btnEquipamentos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnEquipamentos.setMnemonic('E');
        btnEquipamentos.setText(Configs.ConfigTela.getConfig("btnPainelEquipamento"));
        btnEquipamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipamentos.setFocusable(false);
        btnEquipamentos.setName("Equipamentos"); // NOI18N

        btnMateriais.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMateriais.setMnemonic('M');
        btnMateriais.setText(Configs.ConfigTela.getConfig("btnPainelMaterial"));
        btnMateriais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMateriais.setFocusable(false);
        btnMateriais.setName("Materiais"); // NOI18N

        btnCursos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCursos.setMnemonic('C');
        btnCursos.setText(Configs.ConfigTela.getConfig("btnPainelUnidadeCurso"));
        btnCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCursos.setFocusable(false);
        btnCursos.setName("Unidade/Curso"); // NOI18N

        jcbSituacao.setFont(GraphicsConstants.FONT_INPUT);
        jcbSituacao.setModel(new DefaultComboBoxModel<String>(Equipamentos.STATUS_1));
        jcbSituacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbSituacao.setFocusable(false);

        jcbTipo.setFont(GraphicsConstants.FONT_INPUT);
        jcbTipo.setModel(new DefaultComboBoxModel<Tipo>(Pessoa.Tipo.values()));
        jcbTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbTipo.setFocusable(false);

        jcbAtivo.setFont(GraphicsConstants.FONT_INPUT);
        jcbAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ativos", "Desativados" }));
        jcbAtivo.setSelectedIndex(1);
        jcbAtivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbAtivo.setFocusable(false);

        txtPesquisa.setFont(GraphicsConstants.FONT_INPUT);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/lupa.png"))); // NOI18N

        btnLimparFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/master-clean2.png"))); // NOI18N
        btnLimparFiltros.setToolTipText("Limpar Filtros");
        btnLimparFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparFiltros.setFocusable(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/ios7-printer.png"))); // NOI18N
        btnImprimir.setToolTipText("Gerar Relatório");
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.setEnabled(false);
        btnImprimir.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 157, Short.MAX_VALUE)
                        .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDataAcesso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparFiltros)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimparFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lbDataAcesso)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void limparFiltros() {
        this.txtPesquisa.setText(null);
        this.jcbAtivo.setSelectedIndex(1);
        this.jcbSituacao.setSelectedIndex(0);
        this.jcbTipo.setSelectedIndex(0);
    }
    
    public JLabel getLbDataAcesso() {
        return lbDataAcesso;
    }

    public JPanel getJpPaginacao() {
        return jpPaginacao;
    }

    public JTable getTblAdministrador() {
        return tblAdministrador;
    }

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    public JButton getBtnCursos() {
        return btnCursos;
    }

    public JButton getBtnEquipamentos() {
        return btnEquipamentos;
    }

    public JButton getBtnMateriais() {
        return btnMateriais;
    }

    public JButton getBtnPessoas() {
        return btnPessoas;
    }

    public JButton getBtnUsuarios() {
        return btnUsuarios;
    }

    public JComboBox getJcbSituacao() {
        return jcbSituacao;
    }

    public JComboBox<Tipo> getJcbTipo() {
        return jcbTipo;
    }

    public JComboBox<String> getJcbAtivo() {
        return jcbAtivo;
    }

    public JButton getBtnLimparFiltros() {
        return btnLimparFiltros;
    }

    public JButton getBtnImprimir() {
        return btnImprimir;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnEquipamentos;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimparFiltros;
    private javax.swing.JButton btnMateriais;
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbAtivo;
    private javax.swing.JComboBox jcbSituacao;
    private javax.swing.JComboBox<Tipo> jcbTipo;
    private javax.swing.JPanel jpPaginacao;
    private javax.swing.JLabel lbDataAcesso;
    private javax.swing.JTable tblAdministrador;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
