/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.model.vo.Equipamentos;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaSelecionarEquipamento extends javax.swing.JDialog {

    /**
     * Creates new form TelaSelecionarSolicitante
     *
     * @param parent
     * @param modal
     */
    public TelaSelecionarEquipamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.tblEquipamento.getColumnModel().getColumn(0).setMaxWidth(150);
        this.tblEquipamento.getColumnModel().getColumn(0).setMinWidth(120);
        this.tblEquipamento.getColumnModel().getColumn(3).setMaxWidth(120);
        this.tblEquipamento.getColumnModel().getColumn(3).setMinWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbFiltro = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipamento = new javax.swing.JTable();
        jpPaginacao = new JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Equipamento");
        setBackground(GraphicsConstants.COR_FUNDO);
        setModal(true);
        setResizable(false);

        jPanel1.setBackground(GraphicsConstants.COR_FUNDO);
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 330));

        jcbFiltro.setFont(GraphicsConstants.FONT_INPUT);
        jcbFiltro.setModel(new DefaultComboBoxModel<String>(Equipamentos.STATUS_1));
        jcbFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtPesquisa.setFont(GraphicsConstants.FONT_INPUT);

        jPanel2.setBackground(GraphicsConstants.COR_FUNDO);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(GraphicsConstants.COR_FUNDO, 1, true));

        tblEquipamento.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Tombamento", "Tipo", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEquipamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblEquipamento.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblEquipamento.setRowHeight(30);
        tblEquipamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEquipamento.setShowHorizontalLines(false);
        tblEquipamento.setShowVerticalLines(false);
        tblEquipamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblEquipamento);

        jpPaginacao.setBackground(GraphicsConstants.COR_FUNDO);
        jpPaginacao.setPreferredSize(new java.awt.Dimension(529, 42));

        javax.swing.GroupLayout jpPaginacaoLayout = new javax.swing.GroupLayout(jpPaginacao);
        jpPaginacao.setLayout(jpPaginacaoLayout);
        jpPaginacaoLayout.setHorizontalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        jpPaginacaoLayout.setVerticalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    public JTable getTblEquipamento() {
        return tblEquipamento;
    }

    public JComboBox getJcbFiltro() {
        return jcbFiltro;
    }

    public JPanel getJpPaginacao() {
        return jpPaginacao;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcbFiltro;
    private javax.swing.JPanel jpPaginacao;
    private javax.swing.JTable tblEquipamento;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
