/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.util.Configs;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Janilson
 */
public class TelaPaginacao extends javax.swing.JPanel {

    /**
     * Creates new form TelaPaginacao
     */
    public TelaPaginacao() {
        initComponents();

        try {
            final String[] itens = Configs.ConfigTela.getConfig("JcbItens").split(";");
            for (String item : itens) {
                this.jcbQuantidadeItensPorPagina.addItem(Integer.valueOf(item.trim()));
            }
            final int itensPorPagina = Integer.valueOf(Configs.ConfigTela.getConfig("itensPorPagina").trim());
            this.jcbQuantidadeItensPorPagina.setSelectedIndex(itensPorPagina);
        } catch (Exception e) {
            this.jcbQuantidadeItensPorPagina.addItem(10);
            this.jcbQuantidadeItensPorPagina.addItem(100);
            this.jcbQuantidadeItensPorPagina.addItem(1000);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jlbInicio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlbTotalRegistros = new javax.swing.JLabel();
        jlbTotalPaginas = new javax.swing.JLabel();
        jcbQuantidadeItensPorPagina = new javax.swing.JComboBox<>();

        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(633, 45));

        jPanel1.setBackground(GraphicsConstants.COR_FUNDO);
        jPanel1.setPreferredSize(new java.awt.Dimension(633, 45));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/ios7-arrow-back-mini.PNG"))); // NOI18N
        btnAnterior.setMnemonic(KeyEvent.VK_LEFT);
        btnAnterior.setToolTipText(Configs.ConfigTela.getConfig("ToolTipBntAnterior"));
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.setFocusable(false);

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/ios7-arrow-forward-mini.png"))); // NOI18N
        btnProximo.setMnemonic(KeyEvent.VK_RIGHT);
        btnProximo.setToolTipText(Configs.ConfigTela.getConfig("ToolTipBtnProxima"));
        btnProximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProximo.setFocusable(false);

        jLabel8.setText(Configs.ConfigTela.getConfig("lbDe"));
        jLabel8.setFocusable(false);

        jlbInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInicio.setText("0");
        jlbInicio.setFocusable(false);

        jLabel10.setText(Configs.ConfigTela.getConfig("lbPagina"));
        jLabel10.setFocusable(false);

        jLabel11.setText(Configs.ConfigTela.getConfig("lbTotalDeRegistros"));
        jLabel11.setFocusable(false);

        jlbTotalRegistros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTotalRegistros.setText("0");
        jlbTotalRegistros.setFocusable(false);

        jlbTotalPaginas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTotalPaginas.setText("0");
        jlbTotalPaginas.setFocusable(false);

        jcbQuantidadeItensPorPagina.setToolTipText(Configs.ConfigTela.getConfig("ToolTipJcbItens"));
        jcbQuantidadeItensPorPagina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbQuantidadeItensPorPagina.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbQuantidadeItensPorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTotalPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jlbInicio)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jlbTotalRegistros)
                                .addComponent(jlbTotalPaginas))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcbQuantidadeItensPorPagina, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAnterior() {
        return btnAnterior;
    }

    public JButton getBtnProximo() {
        return btnProximo;
    }

    public JLabel getJlbInicio() {
        return jlbInicio;
    }

    public JLabel getJlbTotalPaginas() {
        return jlbTotalPaginas;
    }

    public JLabel getJlbTotalRegistros() {
        return jlbTotalRegistros;
    }

    public JComboBox<Integer> getJcbQuantidadeItensPorPagina() {
        return jcbQuantidadeItensPorPagina;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Integer> jcbQuantidadeItensPorPagina;
    private javax.swing.JLabel jlbInicio;
    private javax.swing.JLabel jlbTotalPaginas;
    private javax.swing.JLabel jlbTotalRegistros;
    // End of variables declaration//GEN-END:variables
}
