/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.model.vo.Pessoa;
import br.com.jsampaio.sigem.model.vo.Pessoa.Tipo;
import br.com.jsampaio.sigem.model.vo.UnidadeCurso;
import br.com.jsampaio.sigem.util.Configs;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaCadastroPessoa extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroSolicitante
     */
    public TelaCadastroPessoa() {
        initComponents();
        this.jpUsuario.setVisible(false);
        this.jcbTipo.removeItem(Pessoa.Tipo.Todos);
        this.jcbTipo.removeItem(Pessoa.Tipo.Administrador);
    }

    /**
     *
     * @return
     */
    public Pessoa getPessoa() {
        final Pessoa pessoa = new Pessoa();
        try {
            pessoa.setMatricula(Long.valueOf(this.txtMatricula.getText().trim()));
        } catch (NumberFormatException n) {}
        pessoa.setNome(this.txtNome.getText().trim());
        pessoa.setTipo((Tipo) this.jcbTipo.getSelectedItem());
        pessoa.setEmail(this.txtEmail.getText().trim());
        pessoa.setTelefone(this.txtTelefone.getText().trim());

        final UnidadeCurso unidadeCurso = new UnidadeCurso();
        if (!this.txtUnidadeCurso.getText().trim().isEmpty()) {
            unidadeCurso.setCodigo(Long.valueOf(this.txtUnidadeCurso.getText().split("-")[0].trim()));
            unidadeCurso.setUnidadeCurso(this.txtUnidadeCurso.getText().split("-")[0].trim());

            pessoa.setUnidadeCurso(unidadeCurso);
        }

        return pessoa;
    }

    public void preencherCamposAtualizacao(Pessoa pessoa) {
        this.txtEmail.setText(pessoa.getEmail());
        this.txtMatricula.setText(String.valueOf(pessoa.getMatricula()));
        this.txtNome.setText(pessoa.getNome());
        this.txtTelefone.setText(pessoa.getTelefone());
        this.txtUnidadeCurso.setText(pessoa.getUnidadeCurso().toString());
        this.jcbTipo.setSelectedItem(pessoa.getTipo());
    } 
    
    public void limparCampos() {
        this.txtNome.setText(null);
        this.txtMatricula.setText(null);
        this.txtEmail.setText(null);
        this.txtTelefone.setText(null);

        this.txtUnidadeCurso.setText(null);
        this.txtSenha.setText(null);
        this.txtLogin.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabelFone = new javax.swing.JLabel();
        btnPesquisarUnidadeCurso = new javax.swing.JButton();
        btnLimapar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jpUsuario = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        jLabelFone3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabelFone4 = new javax.swing.JLabel();
        txtUnidadeCurso = new javax.swing.JTextField();
        jLabelFone2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabelFone1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        lbDataAcesso = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();

        setBackground(GraphicsConstants.COR_FUNDO);

        jLabel1.setFont(GraphicsConstants.FONT_TITULO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(Configs.ConfigTela.getConfig("lbTituloPessoa"));

        jLabel8.setFont(GraphicsConstants.FONT_LABEL);
        jLabel8.setText(Configs.ConfigTela.getConfig("lbMatriculaPessoa"));

        txtMatricula.setFont(GraphicsConstants.FONT_INPUT);

        jLabelFone.setFont(GraphicsConstants.FONT_LABEL);
        jLabelFone.setText(Configs.ConfigTela.getConfig("lbTelefonePessoa"));

        btnPesquisarUnidadeCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/lupa2.png"))); // NOI18N
        btnPesquisarUnidadeCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLimapar.setFont(GraphicsConstants.FONT_BOTAO);
        btnLimapar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/master-clean2.png"))); // NOI18N
        btnLimapar.setText(Configs.ConfigTela.getConfig("btnLimparPessoa"));
        btnLimapar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimapar.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnCadastrar.setFont(GraphicsConstants.FONT_BOTAO);
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/save-icon-52.png"))); // NOI18N
        btnCadastrar.setText(Configs.ConfigTela.getConfig("btnSalvarPessoa"));
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(101, 57));

        jpUsuario.setBackground(GraphicsConstants.COR_FUNDO);

        txtLogin.setFont(GraphicsConstants.FONT_INPUT);
        txtLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabelFone3.setFont(GraphicsConstants.FONT_LABEL);
        jLabelFone3.setText(Configs.ConfigTela.getConfig("lbUsuarioPessoa"));

        txtSenha.setFont(GraphicsConstants.FONT_INPUT);

        jLabelFone4.setFont(GraphicsConstants.FONT_LABEL);
        jLabelFone4.setText(Configs.ConfigTela.getConfig("lbSenhaPessoa"));

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabelFone3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFone4)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFone3)
                    .addComponent(jLabelFone4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUnidadeCurso.setEditable(false);
        txtUnidadeCurso.setFont(GraphicsConstants.FONT_INPUT);
        txtUnidadeCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelFone2.setFont(GraphicsConstants.FONT_LABEL);
        jLabelFone2.setText(Configs.ConfigTela.getConfig("lbUCPessoa"));

        txtEmail.setFont(GraphicsConstants.FONT_INPUT);
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtNome.setFont(GraphicsConstants.FONT_INPUT);

        jLabelFone1.setFont(GraphicsConstants.FONT_LABEL);
        jLabelFone1.setText(Configs.ConfigTela.getConfig("lbEmailPessoa"));

        jLabel7.setFont(GraphicsConstants.FONT_LABEL);
        jLabel7.setText(Configs.ConfigTela.getConfig("lbNomePessoa"));

        jLabel15.setFont(GraphicsConstants.FONT_LABEL);
        jLabel15.setText(Configs.ConfigTela.getConfig("lbTipoPessoa"));

        jcbTipo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcbTipo.setModel(new DefaultComboBoxModel<Tipo>(Pessoa.Tipo.values()));
        jcbTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbDataAcesso.setForeground(new java.awt.Color(153, 153, 153));
        lbDataAcesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDataAcesso.setText("Acesso em");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(GraphicsConstants.FONT_INPUT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataAcesso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addComponent(btnLimapar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelFone1)
                                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                        .addComponent(txtEmail))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelFone)
                                    .addComponent(jLabel8)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtTelefone)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFone2)
                                    .addComponent(txtUnidadeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarUnidadeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFone1)
                    .addComponent(jLabelFone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelFone2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarUnidadeCurso)
                    .addComponent(txtUnidadeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimapar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDataAcesso)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnLimapar() {
        return btnLimapar;
    }

    public void setBtnLimapar(JButton btnLimapar) {
        this.btnLimapar = btnLimapar;
    }

    public JComboBox getJcbTipo() {
        return jcbTipo;
    }

    public void setJcbTipo(JComboBox jcbTipo) {
        this.jcbTipo = jcbTipo;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public void setTxtMatricula(JTextField txtMatricula) {
        this.txtMatricula = txtMatricula;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JFormattedTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(JFormattedTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }

    public JPanel getJpUsuario() {
        return jpUsuario;
    }

    public void setJpUsuario(JPanel jpUsuario) {
        this.jpUsuario = jpUsuario;
    }

    public JTextField getTxtLogin() {
        return txtLogin;
    }

    public void setTxtLogin(JTextField txtLogin) {
        this.txtLogin = txtLogin;
    }

    public JPasswordField getTxtSenha() {
        return txtSenha;
    }

    public void setTxtSenha(JPasswordField txtSenha) {
        this.txtSenha = txtSenha;
    }

    public JTextField getTxtUnidadeCurso() {
        return txtUnidadeCurso;
    }

    public JButton getBtnPesquisarUnidadeCurso() {
        return btnPesquisarUnidadeCurso;
    }

    public JLabel getLbDataAcesso() {
        return lbDataAcesso;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimapar;
    private javax.swing.JButton btnPesquisarUnidadeCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelFone1;
    private javax.swing.JLabel jLabelFone2;
    private javax.swing.JLabel jLabelFone3;
    private javax.swing.JLabel jLabelFone4;
    private javax.swing.JComboBox<Tipo> jcbTipo;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JLabel lbDataAcesso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUnidadeCurso;
    // End of variables declaration//GEN-END:variables
}
