/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jsampaio.sigem.view;

import br.com.jsampaio.sigem.util.Configs;
import com.toedter.calendar.JDateChooser;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Janilson
 */
public class TelaDevolucaoEmprestimo extends javax.swing.JPanel {

    /**
     * Creates new form TelaDevolucaoEmprestimo
     */
    public TelaDevolucaoEmprestimo() {
        initComponents();
        
        this.tblDevolucaoEmprestimo.getColumnModel().getColumn(0).setMaxWidth(110);
        this.tblDevolucaoEmprestimo.getColumnModel().getColumn(0).setMinWidth(110);        
        
        this.tblDevolucaoEmprestimo.getColumnModel().getColumn(1).setMaxWidth(250);
        this.tblDevolucaoEmprestimo.getColumnModel().getColumn(1).setMinWidth(250);        
        
        this.tblDevolucaoEmprestimo.getColumnModel().getColumn(5).setMaxWidth(120);
        this.tblDevolucaoEmprestimo.getColumnModel().getColumn(5).setMinWidth(120);
        
        this.txtDataInicial.getCalendarButton().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        ((JTextField) this.txtDataInicial.getDateEditor().getUiComponent()).setEditable(false);
        ((JTextField) this.txtDataInicial.getDateEditor().getUiComponent()).setFont(GraphicsConstants.FONT_INPUT);
        this.txtDataFinal.getCalendarButton().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        ((JTextField) this.txtDataFinal.getDateEditor().getUiComponent()).setEditable(false);
        ((JTextField) this.txtDataFinal.getDateEditor().getUiComponent()).setFont(GraphicsConstants.FONT_INPUT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmPopUpDevolucaoEmprestimo = new javax.swing.JPopupMenu();
        jmiPopUpVisualizar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiPopUpDevolucaoEmprestimo = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        lbDataAcesso = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDataInicial = new com.toedter.calendar.JDateChooser();
        txtDataFinal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevolucaoEmprestimo = new javax.swing.JTable();
        jpPaginacao = new JPanel();
        btnVisualizar = new javax.swing.JButton();
        btnConfirmarDevolucao = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnLimparFiltros = new javax.swing.JButton();

        jmiPopUpVisualizar.setText("Visualizar");
        jmiPopUpVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmPopUpDevolucaoEmprestimo.add(jmiPopUpVisualizar);
        jmPopUpDevolucaoEmprestimo.add(jSeparator1);

        jmiPopUpDevolucaoEmprestimo.setText("Confirmar Devolução");
        jmiPopUpDevolucaoEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmPopUpDevolucaoEmprestimo.add(jmiPopUpDevolucaoEmprestimo);

        setBackground(GraphicsConstants.COR_FUNDO);

        jLabel2.setFont(GraphicsConstants.FONT_TITULO);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(Configs.ConfigTela.getConfig("lbTituloDevolucao"));

        lbDataAcesso.setForeground(new java.awt.Color(153, 153, 153));
        lbDataAcesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDataAcesso.setText("Acesso em");

        txtPesquisa.setFont(GraphicsConstants.FONT_INPUT);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/ic_action_search_small.png"))); // NOI18N

        jLabel3.setFont(GraphicsConstants.FONT_LABEL);
        jLabel3.setText(Configs.ConfigTela.getConfig("lbDevolucaoDataInicial"));

        jLabel4.setFont(GraphicsConstants.FONT_LABEL);
        jLabel4.setText(Configs.ConfigTela.getConfig("lbDevolucaoDataFinal"));

        jPanel1.setBackground(GraphicsConstants.COR_FUNDO);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(GraphicsConstants.COR_FUNDO, 1, true));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDevolucaoEmprestimo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblDevolucaoEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Protocolo", "Solicitante", "Data emprestimo", "Data Devolução Prevista", "Data Devolução Efetivada", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDevolucaoEmprestimo.setComponentPopupMenu(jmPopUpDevolucaoEmprestimo);
        tblDevolucaoEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDevolucaoEmprestimo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDevolucaoEmprestimo.setShowHorizontalLines(false);
        tblDevolucaoEmprestimo.setShowVerticalLines(false);
        tblDevolucaoEmprestimo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDevolucaoEmprestimo);

        jpPaginacao.setBackground(GraphicsConstants.COR_FUNDO);
        jpPaginacao.setPreferredSize(new java.awt.Dimension(529, 42));

        javax.swing.GroupLayout jpPaginacaoLayout = new javax.swing.GroupLayout(jpPaginacao);
        jpPaginacao.setLayout(jpPaginacaoLayout);
        jpPaginacaoLayout.setHorizontalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        jpPaginacaoLayout.setVerticalGroup(
            jpPaginacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        btnVisualizar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVisualizar.setText(Configs.ConfigTela.getConfig("btnDevolucaoVisualizar"));
        btnVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnConfirmarDevolucao.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnConfirmarDevolucao.setText(Configs.ConfigTela.getConfig("btnDevolucaoConfirmar"));
        btnConfirmarDevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLimparFiltros.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLimparFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigem/Image/master-clean2.png"))); // NOI18N
        btnLimparFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimparFiltros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jpPaginacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConfirmarDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnLimparFiltros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(97, 97, 97))
                                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbDataAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public JLabel getLbDataAcesso() {
        return lbDataAcesso;
    }

    public JPopupMenu getJmPopUpDevolucaoEmprestimo() {
        return jmPopUpDevolucaoEmprestimo;
    }

    public JMenuItem getJmiPopUpDevolucaoEmprestimo() {
        return jmiPopUpDevolucaoEmprestimo;
    }

    public JMenuItem getJmiPopUpVisualizar() {
        return jmiPopUpVisualizar;
    }

    public JTable getTblDevolucaoEmprestimo() {
        return tblDevolucaoEmprestimo;
    }

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    public JButton getBtnVisualizar() {
        return btnVisualizar;
    }

    public JButton getBtnConfirmarDevolucao() {
        return btnConfirmarDevolucao;
    }

    public JButton getBtnLimparFiltros() {
        return btnLimparFiltros;
    }

    public JDateChooser getTxtDataFinal() {
        return txtDataFinal;
    }

    public JDateChooser getTxtDataInicial() {
        return txtDataInicial;
    }

    public JPanel getJpPaginacao() {
        return jpPaginacao;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarDevolucao;
    private javax.swing.JButton btnLimparFiltros;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu jmPopUpDevolucaoEmprestimo;
    private javax.swing.JMenuItem jmiPopUpDevolucaoEmprestimo;
    private javax.swing.JMenuItem jmiPopUpVisualizar;
    private javax.swing.JPanel jpPaginacao;
    private javax.swing.JLabel lbDataAcesso;
    private javax.swing.JTable tblDevolucaoEmprestimo;
    private com.toedter.calendar.JDateChooser txtDataFinal;
    private com.toedter.calendar.JDateChooser txtDataInicial;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
